CREATE TABLE groups
(
id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
name VARCHAR(255) NOT NULL,
created DATETIME,
modified DATETIME,
PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE users
(
id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
username VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
group_id INTEGER NOT NULL,
created DATETIME,
modified DATETIME,
PRIMARY KEY (id)
) ENGINE=InnoDB;
