CREATE TABLE groups
(
id SERIAL NOT NULL UNIQUE,
name VARCHAR(255) NOT NULL,
created TIMESTAMP,
modified TIMESTAMP,
PRIMARY KEY (id)
);

CREATE TABLE users
(
id SERIAL NOT NULL UNIQUE,
username VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
group_id INTEGER NOT NULL,
created TIMESTAMP,
modified TIMESTAMP,
PRIMARY KEY (id)
);
